# Run docker image, mounting/running service source ("rundev" vs "runpkg")

# In Order to Run Docker in interactive mode
# 1. uncomment/comment to replace bwa_server.py with /bin/bash
# 2. execute command:  bash$ docker-compose run --rm magen_policy

version: "2"

networks:
  default:
    external:
      name: magen_net

services:
  magen_policy:
    build: .
    image: magen_policy:v1.0
    container_name: magen_policy
    command: bash -c '(echo "LAUNCHING MAGEN_POLICY CONTAINER.  NOTE -- OUTPUT ALSO LOGGED UNDER DIR=policy/.. (WORKSPACE ROOT) TO policy_server.log FILE AND TO logs/policy_servers_logs/ SUBDIRECTORY" && ../policy_scripts/policy_server_wrapper.sh -mode operational --data-dir /opt/server/data --log-dir /opt/server/policy_servers_logs) 2>&1 | tee -a ../policy_server.log'
    #command: /bin/bash
    environment:
      - DATADOG_API_KEY
      - DATADOG_APP_KEY
    ports:
      - "5000:5000"
      - "5003:5003"
    volumes:
      - ../..:/opt/server
    stdin_open: true
    tty: true
    networks:
      - default
  magen_mongo:
    image: mongo:latest
    container_name: magen_mongo
    networks:
      - default
