dist: trusty
sudo: required

services:
  - docker

notifications:
  email:
    recipients:
      - magen-build@cisco.com
    on_success: always # default: change
    on_failure: always # default: always

# branch blocklist/safelist
branches:
  except:
    - jcg/dev
    - gibson/onenode

language: python
#python:
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
# command to install dependencies
matrix:
  include:
    - python: 3.6
      env: TO_BUILD=NATIVE
    - python: 3.6
      env: TO_BUILD=DOCKER
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y apt-utils
  - sudo apt-get install -y wget
  - sudo apt-get install -y xz-utils
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y libreadline-dev
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libffi-dev
  - sudo apt-get install -y openssl
  - sudo apt-get install -y net-tools
  - sudo apt-get install -y curl
  - sudo apt-get -qq update

  # If we need, we can update and upgrade distribution

#  - sudo apt-get --yes --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
#  - sudo apt-get --yes --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
  # Python. If needed , we can install from external repo
#  - sudo apt-get -y install python3.6
#  - sudo apt-get -y install python3.6-dev
#  - sudo apt-get -y install python3-pip
#  - sudo -H pip3 install -U pip setuptools
#  - echo "alias python=python3.6" >> ~/.bashrc
#  - pip install sphinx  # chicken-and-egg problem building docs

  # Mongo
  # First purge system from mongo version Travis install (2.4)
  - sudo apt-get purge -y mongodb mongodb-clients mongodb-server mongodb-dev
  - sudo apt-get purge -y mongodb-10gen
  - sudo apt-get autoremove -y
  - sudo rm -rf /var/lib/mongodb/

  # Install Mongo 3.4.4 from tarball, local binary
  # Since Mongo is not installed as system service we will run it as the current user
  # This requires some customization

  #- curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.4.4.tgz
  #- tar -zxvf mongodb-linux-x86_64-3.4.4.tgz
  #- export PATH=`pwd`/mongodb-linux-x86_64-3.4.4/bin:$PATH
  #- sudo mkdir -p /data/db
  #- sudo chown -R `whoami` /data/db
  #- mkdir ~/log
  #- mongod --fork --logpath ~/log/mongodb.log

  # Install mongo from package, as a service.
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - sudo apt-get -qq update
  - sudo apt-get install -y mongodb-org
  - sudo chown -R mongodb:mongodb /var/lib/mongodb
  # Allowing connections to other interfaces besides loopback
  - sudo sed -i.bak '/bindIp/d' /etc/mongod.conf
  - sudo service mongod start
  # Docker compose
  - sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)"
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose -v
  # PIP
  - sudo cp policy/pip.conf /etc/pip.conf
  - cp policy/.pypirc ~/.pypirc
  - sudo apt-get -qq update

install:
  - cd policy
  - if [ "$TO_BUILD" = "NATIVE" ]; then make all; fi
  - if [ "$TO_BUILD" = "DOCKER" ]; then make build_docker; fi

before_script:
  - if [ "$TO_BUILD" = "DOCKER" ]; then sudo docker images; fi
  - printenv

script:
  - if [ "$TO_BUILD" = "NATIVE" ]; then make test_travis; fi
  - if [ "$TO_BUILD" = "DOCKER" ]; then make test_docker_travis; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      make upload
    else
      echo $TRAVIS_BRANCH;
    fi
